export const PROPERTY_PHOTO_IDS = [
  "arbor-crest",
  "gates-on-manhattan",
  "grace-townhomes",
  "grove-park-terrace",
  "thomasville-church-homes",
  "boca-ciega",
  "opa-locka",
  "macedonia",
  "pelican-bay-apartments",
  "walnut-hill-apartments",
  "jefferson-arms",
  "coral-village",
  "holiday-apartments",
  "cumberland-apartments",
  "silver-springs-terrace",
  "river-pointe",
  "breckenridge-village",
  "lexington-arms",
  "la-promesa",
  "crossroads-at-lee-summit",
  "ruby-diamond",
  "star-homes",
  "colonial-estates",
  "marrero-3",
  "windsor-yorkshire-village",
  "north-pointe",
  "granite-bayou",
  "st-charles-place",
  "howell-place",
  "pirates-bend",
  "new-wilmington-arms",
  "anaheim",
  "fairfax",
  "urban-rehab-1",
  "urban-rehab-main-street",
  "midtown-manor",
  "pacific-pointe",
  "granite-ridge",
  "river-garden",
  "columbia-village",
  "forest-view-senior",
  "oak-hills",
] as const;

export type PropertyPhotoId = (typeof PROPERTY_PHOTO_IDS)[number];

export const isPropertyPhotoId = (value: string): value is PropertyPhotoId =>
  PROPERTY_PHOTO_IDS.includes(value as PropertyPhotoId);
